# Generated by Django 3.2.4 on 2021-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_text',
            field=models.TextField(default='', help_text='Краткое описание'),
            preserve_default=False,
        ),
    ]
