# Generated by Django 3.2.4 on 2021-06-28 23:39

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210627_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/default.jpg', upload_to=news.models.news_img_path, verbose_name='Фото'),
        ),
    ]
