# Generated by Django 3.2.4 on 2021-06-25 10:19

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocksSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_block_title', models.CharField(blank=True, help_text='Заголвок 1 блока', max_length=100, null=True)),
                ('first_block_text', models.CharField(blank=True, help_text='Текст 1 блока', max_length=100, null=True)),
                ('second_block_text', models.TextField(blank=True, help_text='Текст 2 блока', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название', max_length=100, null=True)),
                ('text', models.CharField(blank=True, help_text='Текст', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_url', models.CharField(blank=True, help_text='1 Номер Телефона(Ссылка)', max_length=100, null=True)),
                ('s_number_url', models.CharField(blank=True, help_text='2 Номер Телефона(Ссылка)', max_length=100, null=True)),
                ('number', models.CharField(blank=True, help_text='1 Номер Телефона', max_length=100, null=True)),
                ('s_number', models.CharField(blank=True, help_text='2 Номер Телефона', max_length=100, null=True)),
                ('address', models.CharField(blank=True, help_text='Адрес', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondBlockAbouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Заголвок', max_length=100, null=True)),
                ('text', models.CharField(blank=True, help_text='Продолжение', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Format: .svg | FlatIcon', upload_to=settings.models.sms_file_path)),
                ('url', models.URLField(blank=True, help_text='URL', null=True)),
            ],
        ),
    ]
