# Generated by Django 3.2.4 on 2021-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_text', models.CharField(blank=True, help_text='Текст - Производство', max_length=100, null=True)),
                ('service_text', models.TextField(blank=True, help_text='Текст - Сервис', null=True)),
            ],
            options={
                'verbose_name': 'Производство и Сервис',
                'verbose_name_plural': 'Производство и Сервис',
            },
        ),
        migrations.AlterModelOptions(
            name='blockssettings',
            options={'verbose_name': 'Настройка блоков', 'verbose_name_plural': 'Настройка блоков'},
        ),
        migrations.AlterModelOptions(
            name='footercontacts',
            options={'verbose_name': 'Футер - Контакт', 'verbose_name_plural': 'Футер - Контакты'},
        ),
        migrations.AlterModelOptions(
            name='menusetting',
            options={'verbose_name': 'Настройка меню', 'verbose_name_plural': 'Настройка меню'},
        ),
        migrations.AlterModelOptions(
            name='secondblockabouts',
            options={'verbose_name': '2 Блок - Достижение', 'verbose_name_plural': '2 Блок - Достижения'},
        ),
        migrations.AlterModelOptions(
            name='socialmediasetting',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
