# Generated by Django 3.2.4 on 2021-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_pssettings_production_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название', max_length=100, null=True)),
                ('url', models.CharField(blank=True, help_text='Ссылка', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Сторонние ссылки',
                'verbose_name_plural': 'Сторонние ссылки',
            },
        ),
        migrations.AlterField(
            model_name='pssettings',
            name='service_text',
            field=models.TextField(blank=True, help_text='Текст - Услуги', null=True),
        ),
    ]
