# Generated by Django 3.2.4 on 2021-06-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210625_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuurl',
            name='add_to_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
