# Generated by Django 3.2.4 on 2021-06-26 17:05

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_menuurl_add_to_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuurl',
            name='image',
            field=models.ImageField(null=True, upload_to=settings.models.menuurl_img_path),
        ),
    ]
