# Generated by Django 3.2.4 on 2021-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_politics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Информация')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='politics',
            options={'verbose_name': 'Политика конфидециальности', 'verbose_name_plural': 'Политика конфидециальности'},
        ),
    ]
