# Generated by Django 3.2.4 on 2021-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20210626_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_done_message', models.CharField(blank=True, help_text='Сообщение | Обратная связь', max_length=100, null=True)),
                ('application_done_message', models.CharField(blank=True, help_text='Сообщение | Заявка', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Настройка сообщений заявок',
                'verbose_name_plural': 'Настройка сообщений заявок',
            },
        ),
    ]
