# Generated by Django 3.2.4 on 2021-06-27 17:28

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_messagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockssettings',
            name='first_block_text',
            field=models.CharField(blank=True, help_text='Текст 1 блока', max_length=100, null=True, verbose_name='Текст 1 блока'),
        ),
        migrations.AlterField(
            model_name='blockssettings',
            name='first_block_title',
            field=models.CharField(blank=True, help_text='Заголвок 1 блока', max_length=100, null=True, verbose_name='Заголовок 1-го блока'),
        ),
        migrations.AlterField(
            model_name='blockssettings',
            name='second_block_text',
            field=models.TextField(blank=True, help_text='Текст 2 блока', null=True, verbose_name='Текст второго блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='text',
            field=models.TextField(help_text='Информация', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='footercontacts',
            name='name',
            field=models.CharField(blank=True, help_text='Название', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='footercontacts',
            name='text',
            field=models.CharField(blank=True, help_text='Текст', max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес', max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='number',
            field=models.CharField(blank=True, help_text='1 Номер Телефона', max_length=100, null=True, verbose_name='1 Номер Телефона'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='number_url',
            field=models.CharField(blank=True, help_text='1 Номер Телефона(Ссылка)', max_length=100, null=True, verbose_name='1 Ссылка на номер'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='s_number',
            field=models.CharField(blank=True, help_text='2 Номер Телефона', max_length=100, null=True, verbose_name='2 Номер Телефона'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='s_number_url',
            field=models.CharField(blank=True, help_text='2 Номер Телефона(Ссылка)', max_length=100, null=True, verbose_name='2 Ссылка на номер'),
        ),
        migrations.AlterField(
            model_name='menuurl',
            name='add_to_catalog',
            field=models.BooleanField(default=False, verbose_name='Добавлять в каталог'),
        ),
        migrations.AlterField(
            model_name='menuurl',
            name='image',
            field=models.ImageField(null=True, upload_to=settings.models.menuurl_img_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='menuurl',
            name='title',
            field=models.CharField(blank=True, help_text='Название', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='menuurl',
            name='url',
            field=models.CharField(blank=True, help_text='Ссылка', max_length=500, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='messagesettings',
            name='application_done_message',
            field=models.CharField(blank=True, help_text='Сообщение | Заявка', max_length=100, null=True, verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='messagesettings',
            name='feedback_done_message',
            field=models.CharField(blank=True, help_text='Сообщение | Обратная связь', max_length=100, null=True, verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='politics',
            name='text',
            field=models.TextField(help_text='Политика конфидециальности', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pssettings',
            name='production_text',
            field=models.TextField(blank=True, help_text='Текст - Производство', null=True, verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='pssettings',
            name='service_text',
            field=models.TextField(blank=True, help_text='Текст - Услуги', null=True, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='secondblockabouts',
            name='name',
            field=models.CharField(blank=True, help_text='Заголвок', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='secondblockabouts',
            name='text',
            field=models.CharField(blank=True, help_text='Продолжение', max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='file',
            field=models.FileField(help_text='Format: .svg | FlatIcon', upload_to=settings.models.sms_file_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='url',
            field=models.URLField(blank=True, help_text='URL', null=True, verbose_name='Ссылка'),
        ),
    ]
