# Generated by Django 3.2.4 on 2021-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
