# Generated by Django 3.2.4 on 2021-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Показывать в меню'),
        ),
    ]
