# Generated by Django 3.2.4 on 2021-06-27 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='help',
            field=models.CharField(blank=True, default='Ошибка', max_length=500, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, default='Ошибка', max_length=500, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default='Ошибка', max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, default='Ошибка', max_length=500, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, default='Ошибка', max_length=500, verbose_name='Номер телефона или почта'),
        ),
    ]
