# Generated by Django 3.2.4 on 2021-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
