# Generated by Django 3.2.4 on 2021-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvalue_productparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
