# Generated by Django 3.2.4 on 2021-06-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvalue',
            name='productparam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_value', to='catalog.productparam'),
        ),
    ]
