# Generated by Django 3.2.4 on 2021-06-28 11:57

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210627_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=catalog.models.category_img_path, verbose_name='Фото'),
        ),
    ]
