# Generated by Django 3.2.4 on 2021-06-28 12:02

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=catalog.models.subcategory_img_path, verbose_name='Фото'),
        ),
    ]
