# Generated by Django 3.2.4 on 2021-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
